### ISSUE TITLE
Consider removing TikzPictures from dependencies

### ISSUE THREAD

**Issue by rquinn2** [Lecrapouille/MaxPlus.jl#10]
Great library, thanks!

aarch64 systems currently can’t build TikzPictures.jl, making MaxPlus.jl fail to build on such systems to do it being a dependency in Project.toml: https://github.com/MichaelHatherly/Tectonic.jl/issues/13

You can work around it on the individual level with some effort using tectonic_jll from BinaryBuilder, but I don’t see TikZPictures actually used anywhere. And maybe it’s best to keep this as a pure library of MaxPlus functions anyways

**Comment by Lecrapouille** [comment]
@rquinn2 Sorry I did not see immediately your comment. Ok I'll check it

**Comment by Lecrapouille** [comment]
@rquinn2 Tell me if this ok now. I've just merged the dev branch into the master branch, since I promised to @hurak to make in December a release tag. I'll have to make review the code before. I could not last time.

**Comment by Lecrapouille** [comment]
I close feel free to re-open it

**Comment by rquinn2** [comment]
Sorry for the delay.

This fixes it completely. Thank you.
