### ISSUE TITLE
functions.md file not found

### ISSUE THREAD

**Issue by hurak** [Lecrapouille/MaxPlus.jl#4]
It is written towards the bottom of the main README.md file here that 
> The index of (max,+) functions is available at [docs/src/functions.md](https://github.com/Lecrapouille/MaxPlus.jl/blob/dev/docs/src/functions.md)

but the link https://lecrapouille.github.io/MaxPlus.jl/dev/docs/src/functions.md is dead: 
>404 File not found

And yet the file can be found manually, it is at: https://github.com/Lecrapouille/MaxPlus.jl/blob/dev/docs/src/functions.md. Perhaps the automatic configuration of the docs page has not been done correctly.

**Comment by Lecrapouille** [comment]
@hurak Hi ! The link on the README.md (dev branch) is working. The link on the online doc is KO. I'll check how to fix it.

**Comment by Lecrapouille** [comment]
Seems ok now ! And beware on-line docs of the dev branch are outdated and match with the master branch :(

**Comment by hurak** [comment]
Yes, that is what I learnt today by myself. Frustrated a bit that I cannot get the value through `a.λ`, because the dev version uses `a.v` internally while in the notebook it documents the former :-) 

If only you polish this at least a bit, so that it is clear with which version one should do the development, I think I might occasionally contribute with some pieces, be it just some documentation and tutorial material.

**Comment by Lecrapouille** [comment]
@hurak I gave you invitation to be collaborator to this repo. You have to accept it. Then normally you can git push directly on this repo (no more need to fork and do pull request).

**Comment by Lecrapouille** [comment]
@hurak For the `.λ` my father reviewing the code did not like, preferring .v.

At the same time the nightmare (Julia coding speaking) has started when for implementing some (max,+) function we had to introduce (min,+) operations (the lib was supposed to be (max,+) only) then I added the Trop to factorize some code, plus my father did not like my way of adding comments, preferred I move docstrings into a separate file, plus `ε` was ok for (max,+) but how to use it for (min,+). The whole code had to be redone in once, and I gave up that is why the dev branch is still is poor status and Julia package is still referring to the master branch. For example, `MI([1 2; 3 8]) .+ 5` is returning `2×2 Max-Plus dense matrix:` :( I'm a little rusty with Julia but I'll start fixing things. Give me time !

**Comment by hurak** [comment]
I understand perfectly how some design decision can send the project into a direction from which it is difficult to maneuver elegantly any further. But I think it is perfectly normal. Inevitable. Every other project has it like this. But remember that in this case of an open-source project, it must primarily be a fun for you. You do not owe anyone, it is just a fun, isn't it?  No stress :-)

**Comment by Lecrapouille** [comment]
If the dead URLs are fixed, I close this ticket, let's talk on the other.
